import type { Metadata } from "next";
import localFont from "next/font/local";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "swiper/css";
import "@/app/assets/css/bootstrap.min.css";
import "@/app/assets/css/swiper-bundle.min.css";
import "@/app/assets/css/animate.min.css";
import "@/app/assets/css/odometer-theme-default.min.css";
import "@/app/assets/css/fancybox.min.css";
import "@/app/assets/css/magnific-pupup.css";
import "@/app/assets/css/style.css";

import BootstrapClient from "@/components/BootstrapClient";
import Script from "next/script";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BackgroundProvider from "@/components/provider/BackgroundProvider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Offical Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
        <BootstrapClient />
        <BackgroundProvider />
        <Script src="/assets/js/modernizr-3.11.7.min.js" />
        <Script src="/assets/js/jquery-3.6.0.min.js" />
        <Script src="/assets/js/jquery-migrate-3.3.2.min.js" />
        <Script src="/assets/js/bootstrap.min.js" />
        <Script src="/assets/js/magnificpopup.min.js" />
        <Script src="/assets/js/swiper-bundle.min.js" />
        <Script src="/assets/js/tilt.jquery.min.js" />
        <Script src="/assets/js/odometer.min.js" />
        <Script src="/assets/js/isotope.min.js" />
        <Script src="/assets/js/imagesloaded.min.js" />
        <Script src="/assets/js/waypoint.min.js" />
        <Script src="/assets/js/wow.min.js" />
        <Script src="/assets/js/fancybox.min.js" />
        <Script src="/assets/js/jquery.ajaxchimp.min.js" />
        <Script src="/assets/js/main.js" />
        <Script src="/assets/js/home.js" />
      </body>
    </html>
  );
}
